// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfywhksjltdzbkzueuwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeXdoa3NqbHRkemJrenVldXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODg4MzMsImV4cCI6MjA2NzU2NDgzM30.8ePu-29TXW5DPKpYrmO9hKKzzpjJeRQfLcTW2d7J31c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});